### ISSUE TITLE
composer.json - move the calendArt/calendArt dependency to "require" section

### ISSUE THREAD

**Issue by petrofcz** [Calendart/Office365Adapter#27]
... because it does not work without it. Appropriate version should be required (not dev-master)

**Comment by Taluu** [comment]
I'm torn for this, even though without any docs, it can't be clear. IMO, we should require `calendart/calendart` (with appropriate version) with the `calendart/office-adapter`, but having only to require `calendart/office-adapter` would also be good.

I'll move this ASAP, and use a proper version, indeed.
